### ISSUE TITLE
Give more informative error when datasets in pymbar.testsystems are not found

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#142]
If `pymbar-datasets` is not installed and the `PYMBAR_DATASETS` environment variable set correctly, it is possible to get uninformative errors like this:
```
Traceback (most recent call last):
  File "scripts/benchmark_mbar.py", line 36, in <module>
    name, u_kn, N_k, s_n = sysgen()
  File "/Users/choderaj/code/yank/install/lib/python2.7/site-packages/pymbar-2.1.0_beta-py2.7-macosx-10.5-x86_64.egg/pymbar/testsystems/pymbar_datasets.py", line 65, in load_gas_data
    u_kn, N_k, s_n = load_from_hdf(os.path.join(root_dir, name, "%s.h5" % name))
  File "/Users/choderaj/code/yank/install/lib/python2.7/site-packages/pymbar-2.1.0_beta-py2.7-macosx-10.5-x86_64.egg/pymbar/testsystems/pymbar_datasets.py", line 56, in load_from_hdf
    f = tables.File(filename, 'r')
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/tables/file.py", line 791, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3756)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/tables/utils.py", line 157, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
IOError: ``/Users/choderaj/gas-properties/gas-properties.h5`` does not exist
```

**Comment by kyleabeauchamp** [comment]
This script was never meant to be automated in the first place.  I *strongly* believe that we need to postpone automated performance benchmarking.  Performance tuning can depend on the specific optimizations used when building the pre-requisite libraries (numpy, numexpr, blas).  This may require more attention to detail than we can achieve with Jenkins.

**Comment by kyleabeauchamp** [comment]
Also, performance numbers will depend on whether there are other background jobs running on our automation servers.

**Comment by mrshirts** [comment]
I agree that automatically triggered performance testing doesn't make that much sense -- we just need a script that we can run ourselves on a range of corner cases in computation complexity space when we think there might be performance issues.

**Comment by jchodera** [comment]
> Also, performance numbers will depend on whether there are other background jobs running on our automation servers.

True. I've disable that project now.

> This script was never meant to be automated in the first place. 

That's fine, but doesn't `pymbar.testsystems` ship with the `pymbar` conda package here?

**Comment by kyleabeauchamp** [comment]
Sure, we'll keep this issue open as a reminder to improve the error message there.

**Comment by kyleabeauchamp** [comment]
#164
