### ISSUE TITLE
New travis failures

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#258]
A surprising number of new travis failures have started cropping up:
https://travis-ci.org/choderalab/pymbar/jobs/203281507#L1101-L1305

I think it may have to do with an updated `numpy` version:
```
======================================================================
ERROR: pymbar.tests.test_covariance.test_200x50_exponentials
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/pymbar/tests/test_covariance.py", line 59, in test_200x50_exponentials
    _test(data_generator)
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/pymbar/tests/test_covariance.py", line 25, in _test
    name, U, N_k, s_n = data_generator()
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/pymbar/tests/test_covariance.py", line 58, in <lambda>
    data_generator = lambda : load_exponentials(200, 50)
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/pymbar/tests/test_covariance.py", line 21, in load_exponentials
    x_n, u_kn, N_k_output, s_n = test.sample(N_k, mode='u_kn')
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/pymbar/testsystems/exponential_distributions.py", line 134, in sample
    x_kn = np.zeros([self.n_states, N_max], np.float64)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

**Comment by jchodera** [comment]
The failures seem to be due to either `pymbar/testsystems/exponential_distributions.py` line 134:
```
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/pymbar/testsystems/exponential_distributions.py", line 134, in sample
    x_kn = np.zeros([self.n_states, N_max], np.float64)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```
or a change in the API of `numpy.fft`:
```
======================================================================
ERROR: pymbar.tests.test_timeseries.test_statistical_inefficiency_fft
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/pymbar/tests/test_timeseries.py", line 56, in test_statistical_inefficiency_fft
    timeseries.statisticalInefficiency_fft(X[0])
  File "/home/travis/miniconda/conda-bld/pymbar-dev_1487549271959/_t_env/lib/python2.7/site-packages/pymbar/timeseries.py", line 850, in statisticalInefficiency_fft
    np.fft.fftpack._fft_cache.clear()
AttributeError: '_FFTCache' object has no attribute 'clear'
```
Can you take a look, @Lnaden?

**Comment by Lnaden** [comment]
Yeah, I was wondering when this sort of thing would happen. We have been getting `FutureWarnings` for a while now about behavior that would be changed. I'll try to fix them today.
