### ISSUE TITLE
MBAR function error: Total number of samples not equal to the sum of each N_k

### ISSUE THREAD

**Issue by apbhati1** [choderalab/pymbar#267]
I have been trying to implement MBAR using the mbar python module for my analysis. 

I have 10 equilibrium states (0 to 9). I am trying to get the expectation of an observable (A) in state 0 utilising the potential energies collected from all 10 states. I have 400 uncorrelated snapshots from each state. Therefore, I saved the corresponding reduced potentials to a 2-d array "_u_kn[K,N]_", where K = 10 and N = 400. I save the number of snapshots from each state into a 1d array "_N_k[K]_" where each _N_k[k]_ = 400. But, when I call the function "_pymbar.MBAR_" I get the following error message (quoted; in italics).

"_Reading potential energies....
400 lines read, processing 400 snapshots
K (total states) = 10, total samples = 400
Traceback (most recent call last):
  File "mbar_analysis.py", line 65, in <module>
    mbar = pymbar.MBAR(U_kn, N_k, verbose=True)
  File "/home/agastya/miniconda2/lib/python2.7/site-packages/pymbar/mbar.py", line 176, in __init__
    'The sum of all N_k must equal the total number of samples (length of second dimension of u_kn.')_"

The total number of samples from each state is just 400 in my case. I do not have more than 400 values to fill in to the array "_u_kn_". What needs to be done to make it work here?

I have another related question. After initialising MBAR on my simulation data, I intend to calculate the expectation of an observable A in state 0. I understand from the manual that the following function needs to be called for the same: "_mbar.computeExpectations(A_n, u_kn[0,:])_" where, "_A_n_" is a 1d array of size 400 containing the values of the observable in state 0 for all 400 snapshots and "_u_kn[0,:]_" are the corresponding values of reduced potentials from state 0 for all 400 snapshots. Is that correct?

**Comment by Lnaden** [comment]
MBAR works by having the energy of *every* sample from *any* state evaluated at *every other state*. So if you have the 10 states and 400 energies, you will actually have 10*40=4000 total samples. 

The `u_kn` formalism can be thought of like: "Given `K` states and `N` total samples drawn from any number of the states, `u_kn` is the energy of sample `n` evaluated in state `k`." So you will need to evaluate the energy of every sample in every state in order to properly use MBAR. The `N_k` array is still correct in that `N_k` is "how many samples did I draw from each `k`'th state"

If its easier to think about, you can also provide a `u_kln` matrix which is a 3-d matrix of "given sample `n` drawn from state `k`, what is its energy in state `l`?" This is closer to what you have, but MBAR condenses this down to `u_kn` under the hood anyways.

> I intend to calculate the expectation of an observable A in state 0...

So in this case, the `A_n` is "what is the value of the observable `A` for every sample `n`". The function will then return `<A>_k` which is the expectation of `A` evaluated at each state, `k`. 

By default, `computeExpectations` assumes you want to evaluate `<A>` at each state you provided with the initial MBAR creation. However, you don't have to evaluate only at the initialized states.

If `A` is a function of state, you will need to set `state_dependent=True` and providea `A_kn` matrix which is the observable `A` evaluated at each `k`'th state for each `n`'th sample

 If you want to evaluate `<A>_l` at unsampled states `l`, you would provide a `u_ln` energy matrix which is "The energy of every sample `n` evaluated at state `l`." The `L`'th dimension does not have to be the same length as K. 

You could provide a `u_ln` matrix which is `u_ln.shape == (1,N)` where you only provide the energies from the 0'th state you sampled, and you should get the same result as `mbar.computeExpectations(A_n)[0]`


Hopefully this helps and let me know if there are other questions

**Comment by apbhati1** [comment]
Thanks for the description. Its much clearer now. 

Just another small question. My observable is state dependent, but I just want to get its expectation at state `0`. Do I still need to provide the whole `A_kn` matrix (dimensions `K,N`) as an input to the function `computeExpectations` along with `u_ln` (where `u_ln.shape == (1,N)`) or  just `A_ln` (where `A_ln.shape == (1,N)`) would suffice?

**Comment by Lnaden** [comment]
I'm assuming you only care about states you have sampled here, so the set of states `K` is the same set of states `L`, so for the sake of clarity, I'll just work in `K` and `k`. 

If you accept the defaults and only provide an `A`, then the function assumes you want `<A>_k` at all K, since it uses the MBAR input `u_kn` as the energies to compare to, so there are `K` states it evaluates at. In this case, you would still need to provide the whole `A_kn` array to have the function work. Output will then be an array of shape `K` depending on if you set `output` to averages or differences. 

If you only want the one state, assuming its your state 0, then you can either just read the 0'th entry of the `<A>_k` output from defaults, OR you can provide a `u_kn=...` keyword argument to the function where the `u_kn.shape == (1,N)` and `u_kn_passed_in[0,:] = u_kn_to_initilize_mbar[0,:]`. In this case you would then provide only `A_{0,n}`. Then you would just get a single number out `<A>_0` if you had "averages" set for `output`. Handy if you dont have `A` at all states. Note that if you set `output= differences` in this case you would get out a 2d, 1x1 matrix with the single entry of "0"

**Comment by apbhati1** [comment]
Thank you very much for your help. I really appreciate it. 

I am now able to successfully calculate the expectation of observable `A` at any/all sampled states. However, I got stuck while trying to apply the function `computeExpectations` to calculate the expectation of observable at unsampled states. I am assuming here that unsampled states are the ones where we do not have access to the values of observable `A`. So, this would mean that we need to just provide the energy matrix `u_ln` to the function `computeExpectations` and no matrix `A`. Is that correct? If yes, then how (because I understand from the manual that matrix `A` is not an optional argument)?

**Comment by mrshirts** [comment]
> I am assuming here that unsampled states are the ones where we do not
have access to the values of observable A

You always have to be able to calculate A(x).  An unsampled state is one
where you do not perform the simulation. For example, if we do not perform
a simulation when the energy function is U_1(x), we can still estimate it
by calculating U_1(x) and A(x) from simulations performed with different
energy functions.  Try looking at some of the examples for when
expectations at unsampled states are performed.

**Comment by apbhati1** [comment]
I ran the following command to compute expectation of `A` at unsampled state `l`: `mbar.computeExpectations(A_l, U_l, state_dependent=True)`, where `A_l` and `U_l` are the matrices containing the values of the observable and reduced potential at state `l` for all samples. I get the following error using this command:

"Traceback (most recent call last):
  File "mbar_analysis.py", line 108, in <module>
    (A_0, dA_0) = mbar.computeExpectations(A_l, U_l, state_dependent=True) # computing expectation of dV/dl at target state.
  File "/home/agastya/miniconda2/lib/python2.7/site-packages/pymbar/mbar.py", line 902, in computeExpectations
    warning_cutoff=warning_cutoff)
  File "/home/agastya/miniconda2/lib/python2.7/site-packages/pymbar/mbar.py", line 669, in computeExpectationsInner
  np.exp(Log_W_nk), N_k, method=uncertainty_method)
  File "/home/agastya/miniconda2/lib/python2.7/site-packages/pymbar/mbar.py", line 1493, in _computeAsymptoticCovarianceMatrix
    check_w_normalized(W, N_k)
  File "/home/agastya/miniconda2/lib/python2.7/site-packages/pymbar/utils.py", line 361, in check_w_normalized
    (firstbad, column_sums[firstbad], np.sum(badcolumns)))
pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 9 was 0.993236. 1 other columns have similar problems"

Am I doing anything wrong here?

**Comment by apbhati1** [comment]
Just to clarify, I have not used `U_l` while initialising MBAR. Looks like I need to include additional columns in the initialisation matrix `U_kn` and additional element in `N_k` with values `0` for each state `l`. Is that correct? If yes, does the order matter here?

**Comment by Lnaden** [comment]
The `u_kn` matrix to initialize MBAR at minimum must be the energies  such that `Sum N_k = N`, however, you can have additional states in the `u_kn` matrix that you drew 0 samples from and evaluate use them to initialize MBAR as well. so for this argument, assume we have `L` states with 0 samples, and we evaluate the energies of all `N` samples at every `l'th` state, the initial `u_kn` matrix would really be a `u_(k+l)n` matrix and the `N_k=0` for all `L` states. That is one option, and then the observables in each `L` state are estimated based on the states which do have samples drawn from them. In this case, the location of the additional states does matter such that for `u_kn` the `k`'th index should match up to the `k`'th index in `N_k`

The equivalent method is to initialize only with `u_kn` from sampled states, then use functions like `computePerturbedFreeEnergies(u_ln)` to get free energies from the unsampled states. In this case, your output will be be indexed by the order in which the states appear in `u_ln`'s `l`'th index.

As to your question. The `computeExpectations` expects at minimum one argument, that is the `A_n`, the value of the observable `A` at every drawn sample `N`. Additionally, you can provide it a `u_ln` matrix which is the energy of each sample `N` evaluated at however many `L` states you have. Since you only want this observable at a single unsampled state, the following should be true:
* `A_n.shape == N`
* `u_ln.shape == (1,N)` <- your `U_l`

**Comment by apbhati1** [comment]
Thanks for the help and sorry for bothering you with so many questions. 

I did exactly what you have mentioned. I initialised using `U_(k+l)n`, where `K=9`, `L=1`, `N=3600`, `U_(k+l)n.shape == (10,3600)` and `N_k = [400 400 400 400 400 400 400 400 400   0]`. It initialised successfully. 

Then I called the command `mbar.computeExpectations(A_l, U_l, state_dependent=True)` to compute the expectation of `A` at the unsampled state `L`, where `A_l.shape == (1,N)`, `U_l.shape == (1,N)` and `U_l == U_(k+l)n[-1,:]`. I still get the following error: `pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 10 was 0.993236. 1 other columns have similar problems`. I cannot think what is going wrong now. Can you please suggest what may be causing this error?

**Comment by apbhati1** [comment]
I noted an interesting thing here. I got rid of the above error by just changing the order of columns in my `U_(k+l)n` matrix. 

I was consistently getting the above error (sum of W_nk not being equal to 1) when using `U_l == U_(k+l)n[-1,:]` and `N_k[-1] = 0`, where, after initialisation, the final dimensionless free energy matrix `f_k` was such that `f_k[0] = 0; f[1:-1] = a positive number with f_k[k+1] > f_k[k] for any k; f_k[-1] = a negative number`.

Thereafter, I just reran the same script after reordering my `U_(k+l)n` matrix such that `U_l == U_(k+l)n[0:]` and `N_k[0] = 0`, where, after initialisation, `f_k[0] = 0; f_k[1:] = a positive number with f_k[k+1] > f_k[k] for any k`. This time the command `mbar.computeExpectations(A_l, U_l, state_dependent=True)` did not give any error and produced expected output correctly.

`A_l` matrix is the same in both the cases. So, in short, the order of `U_(k+l)n` matrix matters, at least in my case where the trend of increasing values of dimensionless free energies with states breaks on changing the order. I thought might be worth sharing with the developers.

Any comments on that?
