### ISSUE TITLE
Normalized weight matrix doesn't sum to 1 on rows and colums 

### ISSUE THREAD

**Issue by samarjeet** [choderalab/pymbar#276]
I tried the alchemical free energy calculation example for a Lennard Jones fluid (http://openmm.org/tutorials/alchemical-free-energy/) and it crashes with mbar having issues with having non-1 sum for columns and rows for the normalized weight matrix. Tried it with different lambda points and iterations, some of them pass through (after increasing the tolerance in mbar) but most (all except one that I tried) fails in  check_w_normalized.

Traceback (most recent call last):
  File "alchemical-example.py", line 92, in <module>
    [DeltaF_ij, dDeltaF_ij, Theta_ij] = mbar.getFreeEnergyDifferences()
  File "/v/apps/anaconda/4.2.0-py3.5/lib/python3.5/site-packages/pymbar/mbar.py", line 470, in getFreeEnergyDifferences
    np.exp(self.Log_W_nk), self.N_k, method=uncertainty_method)
  File "/v/apps/anaconda/4.2.0-py3.5/lib/python3.5/site-packages/pymbar/mbar.py", line 1496, in _computeAsymptoticCovarianceMatrix
    check_w_normalized(W, N_k)
  File "/v/apps/anaconda/4.2.0-py3.5/lib/python3.5/site-packages/pymbar/utils.py", line 363, in check_w_normalized
    (firstbad, column_sums[firstbad], np.sum(badcolumns)))
pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 5.135352. 10 other columns have similar problems

**Comment by mrshirts** [comment]
This usually means that there's isn't good overlap between the points.  If there's an example data set, we could look at it and figure out better.
