### ISSUE TITLE
pymbar.utils.ParameterError

### ISSUE THREAD

**Issue by xiki-tempula** [choderalab/pymbar#407]
I'm using alchemlyb as an interface to do MBAR calculations, where I found that for a set of dhdl files generated with Gromacs, mbar estimate will fail when using pymbar==3.0.5, giving:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXX/miniconda3/envs/flamel/lib/python3.8/site-packages/alchemlyb/estimators/mbar_.py", line 90, in fit
    out = self._mbar.getFreeEnergyDifferences(return_theta=True)
  File "/Users/XXX/miniconda3/envs/flamel/lib/python3.8/site-packages/pymbar/mbar.py", line 541, in getFreeEnergyDifferences
    Theta_ij = self._computeAsymptoticCovarianceMatrix(
  File "/Users/XXX/miniconda3/envs/flamel/lib/python3.8/site-packages/pymbar/mbar.py", line 1679, in _computeAsymptoticCovarianceMatrix
    check_w_normalized(W, N_k)
  File "/Users/XXX/miniconda3/envs/flamel/lib/python3.8/site-packages/pymbar/utils.py", line 358, in check_w_normalized
    raise ParameterError(
pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 0.000092. 11 other columns have similar problems
```

However, when using pymbar==3.0.dev3 gives the correct answer.

The code to reproduce the problem is:
```
from alchemlyb.parsing.gmx import extract_u_nk
import pandas as pd
u_nk = pd.concat([extract_u_nk('dhdl_{}.xvg'.format(i), T=310) for i in range(11)])
from alchemlyb.estimators import MBAR
MBAR().fit(u_nk)
```

The files are https://drive.google.com/file/d/16bJGCEflqEm5xZhfOQbZ4TSNhorfob4m/view?usp=sharing

**Comment by davidlmobley** [comment]
cc @mrshirts -- same issue as #419 it seems.
